siteinterface_homepage:
    path:     /
    defaults: { _controller: siteinterfaceBundle:Default:index }

siteinterface_support:
    path:     /support
    defaults: { _controller: siteinterfaceBundle:Default:support }


# ACTIONS ENTITES
siteinterface_entite_type:
    path:     /entite/{entite}/{type_related}/{type_field}/{type_values}/{action}/{id}
    defaults: { _controller: siteinterfaceBundle:entite:entitePage, action: null, id: null }

siteinterface_entite:
    path:     /entite/{entite}/{action}/{id}
    defaults: { _controller: siteinterfaceBundle:entite:entitePage, action: null, id: null }

siteinterface_form_action:
    path:     /form-action/{classname}
    defaults: { _controller: siteinterfaceBundle:entite:entitePostFormPage }
    requirements:

siteinterface_pageweb_set_default:
    path:     /pageweb/set-as-default/{id}/{redir}
    defaults: { _controller: siteinterfaceBundle:entite:pageweb_as_default, redir: 'siteinterface_homepage' }

# FILE FORMAT
siteinterface_fileformat_resetall:
    path:     /file-format/{erase}
    defaults: { _controller: siteinterfaceBundle:entite:resetFileFormats, erase: false }

# MENUS
siteinterface_menus:
    path:     /menus/list/{name}
    defaults: { _controller: siteinterfaceBundle:menus:index, name: 'all' }

siteinterface_menus_action:
    path:     /menus/action/{action}/{bundle}/{name}
    defaults: { _controller: siteinterfaceBundle:menus:action, name: null }

siteinterface_ajax_modify:
    path:     /menus/ajax-modify/{bundle}/{name}
    defaults: { _controller: siteinterfaceBundle:menus:modify }
