parameters:
    memory_limit: 2048M
    cropperInfo:
        # Mémoire PHP allouée
        memory_limit: 2048M
        #largeur de l'image pour cropper
        modelWidth: 800
        # formats requis pour les champs des différentes entités
        # si aucun format n'est défini ici, le format cropper sera libre
        formats:
            ### ALL DEFAULT
            default:
                # - null # ==> format libre
                - [1024, 768]
                - [768, 1024]
                - [1024, 1024]
            ### SITE
            site:
                image:
                    - [260, 118]
                logo:
                    - [400, 400]
                favicon:
                    - [16, 16]
                adminLogo:
                    - [137, 52]
            ### EVENEMENT
            evenement:
                image:
                    # - null
                    - [2048, 1024]
                    - [1024, 768]
                    - [768, 1024]
            ### ITEM
            item:
                image:
                    - [200, 400]
            article:
                image: 
                    - [1000, 700]
                    - [1000, 1000]
                    - [700, 1000]
            slide:
                image: 
                    - [1000, 600]
            pageweb:
                image:
                    - [1024, 600]
                    - [768, 1024]
                    - [1024, 1024]
            section:
                image:
                    - [1024, 600]
                    - [1024, 1024]
                    - null
            fiche:
                image:
                    - [800, 600]
                    - [800, 800]
                    - [600, 800]
            ficherecette:
                image:
                    - [1024, 600]
                    - [800, 800]
                    - [600, 800]
            ficheboisson:
                image:
                    - [800, 600]
                    - [800, 800]
                    - [600, 800]
                    - [450, 800]
                    # - null
            ### TIER
            tier:
                image:
                    - [800, 600]
                logo:
                    - [400, 400]
            marque:
                image:
                    - [800, 600]
                logo:
                    - [400, 400]
            boutique:
                image:
                    - [800, 600]
                logo:
                    - [400, 400]
            reseau:
                image:
                    - [800, 600]
                logo:
                    - [400, 400]
            ### CATEGORIE
            categorie:
                image:
                    - [132, 132]
            ### USER
            User:
                avatar:
                    - [400, 400]


