_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /_error

_main:
    resource: routing.yml

# site_admin:
#     resource: "@siteadminsiteBundle/Resources/config/routing.yml"
#     prefix:   /{_locale}/admin
#     defaults: { _locale: %locale% }
#     requirements:
#         _locale: %default_locales%

# main_home:
#     pattern: /{_locale}
#     defaults: { _controller: sitesiteBundle:Default:index, _locale: %locale% }
#     requirements:
#         _locale: %default_locales%

# site_site:
#     resource: "@sitesiteBundle/Resources/config/routing.yml"
#     prefix:   /{_locale}
#     defaults: { _locale: %locale% }
#     requirements:
#         _locale: %default_locales%
