siteadmin_homepage:
    path:     /
    defaults: { _controller: siteadminsiteBundle:Default:index }

siteadmin_support:
    path:     /support
    defaults: { _controller: siteadminsiteBundle:Default:support }

# SUPER ADMIN
siteadmin_sadmin_index:
    path:     /superadmin
    defaults: { _controller: siteadminsiteBundle:superadmin:index }

siteadmin_sadmin_panier:
    path:     /superadmin/panier/tests
    defaults: { _controller: siteadminsiteBundle:superadmin:panierTest }

siteadmin_sadmin_sessiondata:
    path:     /superadmin/sessiondata
    defaults: { _controller: siteadminsiteBundle:superadmin:sessiondata }

siteadmin_sadmin_routes:
    path:     /superadmin/routes
    defaults: { _controller: siteadminsiteBundle:superadmin:routes }

siteadmin_sadmin_services:
    path:     /superadmin/services/{service}
    defaults: { _controller: siteadminsiteBundle:superadmin:services }

siteadmin_sadmin_bundles:
    path:     /superadmin/bundles
    defaults: { _controller: siteadminsiteBundle:superadmin:bundles }

siteadmin_sadmin_entities:
    path:     /superadmin/entities/{entity}/{field}
    defaults: { _controller: siteadminsiteBundle:superadmin:entities, entity: null, field: null }

# GENERATION SITE
generate:
    path:     /generate/{action}/{entite}
    defaults: { _controller: siteadminsiteBundle:generate:index, action: null, entite: null }

# ACTIONS ENTITES
siteadmin_entite_type:
    path:     /entite-type/{entite}/{type_related}/{type_field}/{type_values}/{action}/{id}
    defaults: { _controller: siteadminsiteBundle:entite:entitePage, action: null, id: null }

siteadmin_entite_repo:
    path:     /entite-repo/{entite}/{method}/{params}/{repository}
    defaults: { _controller: siteadminsiteBundle:entite:entitePage, params: null, repository: null }

siteadmin_entite:
    path:     /entite/{entite}/{action}/{id}
    defaults: { _controller: siteadminsiteBundle:entite:entitePage, action: null, id: null }

siteadmin_form_action:
    path:     /form-action/{classname}
    defaults: { _controller: siteadminsiteBundle:entite:entitePostFormPage }

# CHECK
siteadmin_form_checknesteds:
    path:     /check-nesteds
    defaults: { _controller: siteadminsiteBundle:entite:checkAllNestedPositions }

siteadmin_check:
    path:     /check-entite/{entite}
    defaults: { _controller: siteadminsiteBundle:entite:checkAllEntities }

# entite sets
siteadmin_set_default:
    path:     /entite-set/as-default/{id}/{entite}/{redir}
    defaults: { _controller: siteadminsiteBundle:entite:entite_as_default, redir: 'siteadmin_homepage' }

siteadmin_set_vendable:
    path:     /entite-set/as-vendable/{id}/{entite}/{redir}
    defaults: { _controller: siteadminsiteBundle:entite:entite_as_vendable, redir: 'siteadmin_homepage' }

# CALENDAR
siteadmin_calendar_viewer:
    path:     /calendar/viewer/{itemSlug}/{class}
    defaults: { _controller: siteadminsiteBundle:calendar:calendarViewer }

siteadmin_calendar_edit:
    path:     /calendar/edit/{eventSlug}
    defaults: { _controller: siteadminsiteBundle:calendar:calendarEdit }

siteadmin_calendar_ajax:
    path:     /ajax-calendar/{itemSlug}/{class}
    defaults: { _controller: siteadminsiteBundle:calendar:ajaxCalendar }
    # methods: ['post']

siteadmin_calendar_feed:
    path:     /feed-calendar/{itemSlug}/{class}
    defaults: { _controller: siteadminsiteBundle:calendar:ajaxFeed }
    # methods: ['post']


# FACTURE
siteadmin_facture_changestate:
    path:     /change-state-facture/{factureId}/{state}
    defaults: { _controller: siteadminsiteBundle:facture:changeStateFacture }
    # methods: ['post']

# ---- external facture actions ------ #
site_ext_facture_changestate:
    path:     /external/change-state-facture/{factureId}/{state}/{username}/{key}
    defaults: { _controller: siteadminsiteBundle:factureExt:changeStateFacture }
    requirements:
        state: '[0-6]'

site_ext_facture_delete:
    path:     /external/delete-test-facture/{factureId}/{username}/{key}
    defaults: { _controller: siteadminsiteBundle:factureExt:deleteTestFacture }



#CATEGORIES
siteadmin_list_categorie:
    path:     /categorie/list/{type_related}/{type_field}/{type_values}
    defaults: { _controller: siteadminsiteBundle:categorie:categorieList, type_related: null, type_field: null, type_values: null }

siteadmin_repo_categorie:
    path:     /categorie/repo/{method}/{repoParams}
    defaults: { _controller: siteadminsiteBundle:categorie:categorieRepo, repoParams: null }

siteadmin_show_categorie:
    path:     /categorie/show/{id}
    defaults: { _controller: siteadminsiteBundle:categorie:categorieShow }
    requirements:
        rootParent: \d+

siteadmin_edit_categorie:
    path:     /categorie/edit/{id}
    defaults: { _controller: siteadminsiteBundle:categorie:categorieEdit }
    requirements:
        rootParent: \d+

siteadmin_create_categorie:
    # type root : rootParent = null
    # autres types : type d'un parent root = préciser son id
    path:     /categorie/create/{rootParent}
    defaults: { _controller: siteadminsiteBundle:categorie:categorieCreate, rootParent: null }
    requirements:
        rootParent: \d+

siteadmin_form_categorie:
    path:     /categorie-form-action
    defaults: { _controller: siteadminsiteBundle:categorie:postform }
    # methods: ['POST']

categorie_check_types:
    path:     /categorie/check/types
    defaults: { _controller: siteadminsiteBundle:categorie:checkCategoriesTypes }

categorie_ajax_data:
    path:     /categorie/ajax-data/{id}/{types}/{groups}
    defaults: { _controller: siteadminsiteBundle:categorie:ajaxData, id: null, types: 'all', groups: null }

ajax_data_sort_construct:
    path:     /sorting-UI/ajax/construct
    defaults: { _controller: siteadminsiteBundle:ajaxqueries:ajaxconstruct }

ajax_data_sort:
    path:     /sorting-UI/ajax
    defaults: { _controller: siteadminsiteBundle:ajaxqueries:ajaxsort }


# MENUS
siteadmin_menus:
    path:     /menus/{name}
    defaults: { _controller: siteadminsiteBundle:menus:index, name: 'all' }

siteadmin_menus_action:
    path:     /menus/action/{action}/{bundle}/{name}/{id}
    defaults: { _controller: siteadminsiteBundle:menus:action, name: null, id: null }

siteadmin_ajax_modify:
    path:     /menus/ajax-modify/{bundle}/{name}
    defaults: { _controller: siteadminsiteBundle:menus:modify }

siteadmin_ajax_maxDepth:
    path:     /menus/ajax-maxDepht/{bundle}/{name}/{value}
    defaults: { _controller: siteadminsiteBundle:menus:changeMaxDepth }

# USERS
siteUser_users:
    path:     /users/{type}/{action}/{params}
    defaults: { _controller: siteUserBundle:Default:index, type: 'all', action: 'list', params: null }

siteUser_info:
    path:     /user/show/{username}
    defaults: { _controller: siteUserBundle:Default:show }

siteUser_edit:
    path:     /user/edit/{username}
    defaults: { _controller: siteUserBundle:Default:edit }

siteUser_delete:
    path:     /user/delete/{username}
    defaults: { _controller: siteUserBundle:Default:delete }

siteUser_check_messagescollaborators:
    path:     /user/check/messagescollaborators/{repar}
    defaults: { _controller: siteadminsiteBundle:superadmin:checkMessagesCollaborators, repar: false }

# MEDIA / IMAGES / PDF
siteMedia_saveRawFile:
    path:     /media/save-raw-file/{entityShortName}
    defaults: { _controller: siteadminsiteBundle:media:persistRawImage }
    # requirements:
    #     entityShortName: image|pdf

# siteMedia_action:
#     path:     /media/action/{action}
#     defaults: { _controller: siteadminsiteBundle:media:action }
