<?php

namespace site\adminsiteBundle\Entity;

use Labo\Bundle\AdminBundle\Entity\tierRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * marqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class marqueRepository extends tierRepository {

	/** Renvoie la(les) valeur(s) par défaut --> ATTENTION : dans un array()
	 * @param $defaults = liste des éléments par défaut
	 */
	public function defaultVal() {
		return $this->defaultValAsClosure()->getQuery()->getResult();
	}

}
