<?php

namespace site\adminsiteBundle\Entity;

use Labo\Bundle\AdminBundle\Entity\itemRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * pagewebRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pagewebRepository extends itemRepository {

	public function defaultVal() {
		return array();
	}

	public function findDefaultPage() {
		$qb = $this->defaultValAsClosure();
		$qb->select(self::ELEMENT.' pageweb');
		$qb->leftJoin(self::ELEMENT.'.image', 'image')->addSelect('image.id image_id');
		$qb->leftJoin(self::ELEMENT.'.diaporama', 'diaporama')->addSelect('diaporama.id diaporama_id');
		return $qb->getQuery()->getArrayResult();
	}

	public function getPageBySlug($itemSlug) {
		$qb = $this->createQueryBuilder(self::ELEMENT);
		$this->contextStatut($qb);
		$qb->where(self::ELEMENT.'.slug = :slug')
			->setParameter('slug', $itemSlug)
			;
		$qb->select(self::ELEMENT.' pageweb');
		$qb->leftJoin(self::ELEMENT.'.image', 'image')->addSelect('image.id image_id');
		$qb->leftJoin(self::ELEMENT.'.diaporama', 'diaporama')->addSelect('diaporama.id diaporama_id');
		return $qb->getQuery()->getArrayResult();
	}

	public function findPaniervalid() {
		$qb = $this->createQueryBuilder(self::ELEMENT);
		$qb->where($qb->expr()->orX($qb->expr()->like(self::ELEMENT.'.modele', $qb->expr()->literal('%/paniervalid.html.twig'))));
		$this->contextStatut($qb);
		return $qb->getQuery()->getOneOrNullresult();
	}


}
