site_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: siteUserBundle:Default:index }

change_user_language:
    path:     /change-user-language/{language}/{user}
    defaults: { _controller: siteUserBundle:Default:changeUserLanguage, user: null }
    requirements:
        language: %default_locales%