<?php

namespace site\adminBundle\Entity;

use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\ClassMetadata;

/**
 * fileFormatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fileFormatRepository extends EntityRepository {


	// REQUESTS FOR FORMS

	public function findActifs() {
		$qb = $this->createQueryBuilder('element');
		$qb->where('element.enabled = :enabled')
			->setParameter('enabled', 1);
		return $qb;
	}

}
